from flask import Flask, render_template
from model import get_marks


app = Flask(__name__)

@app.route("/", methods=["GET"])
def hello():
    question = 'What Is Image Transform?'
    answer = 'An image can be expanded in terms of a discrete set of basis arrays called basis images. Hence, these basis images can be generated by unitary matrices. An NxN image can be viewed as an N^2×1 vector. It provides a set of coordinates or basis vectors for vector space.'
    marks = get_marks(question, answer)
    return jsonify(" Marks: " + str(marks))




